### ISSUE TITLE
项目跑起来了一直识别不了，返回null一直

### ISSUE THREAD

**Issue by fixedyangsir** [AleynP/LPR#1]

**Comment by aleyn97** [comment]
是不是 识别框的原因，那个识别框我没做屏幕适配，所以把车牌放在识别框之外，其他地方试一下，或者改下Demo 里边的代码，不要截取识别框的内容，弄成全屏识别

**Comment by fixedyangsir** [comment]
可能是，还是很感谢提供集成的方法，已用官方demo,那个识别模型，感觉对新能源不太准确，不知你发现没有

**Comment by aleyn97** [comment]
是的，应该是那个训练模型，对新能源训练的不够多。
